version: '3.1'
services:
  mongo:
    image: mongo:4.0.25
    container_name: cortex-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
  cortex-gateway:
    container_name: cortex-gateway
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "dev"
    ports:
    - 8080:8080
    command:
      - -gateway.distributor.address=http://localhost:9400
      - -gateway.query-frontend.address=http://localhost
      - -gateway.auth.jwt-secret=SUPERSECRET
      - -server.http-listen-port=8080
      - -database.uri=mongodb://admin:admin@mongo:27017
    environment:
      KEYCLOAK_PROVIDER_URL: ${KEYCLOAK_PROVIDER_URL}
      CLIENT_SECRET: ${CLIENT_SECRET}
    depends_on:
      - mongo
volumes:
  mongodb_data:
    driver: local
