apiVersion: 1
datasources:
- name: Docker Host
  access: proxy
  orgId: 0
  isDefault: true
  jsonData: 
    httpHeaderName1: "Authorization"
  secureJsonData: 
    httpHeaderValue1: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZW5hbnRfaWQiOiJjb3J0ZXgtZ2F0ZXdheSIsImF1ZGllbmNlIjpudWxsLCJ2ZXJzaW9uIjpudWxsfQ.OtOHzKW3u2iRSUesCRMs8VVxcWZc4yP0xuej-9oPUGyaUv9BqGnNbGK8WCJ25XsgVLxfe_H5Smbg0k9oaqR_Lg"
  type: "prometheus"
  url: "http://host.docker.internal"
  version: 1