global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 15s
  evaluation_interval: 15s
  # external_labels:
  #  - __replica__: $${MY_POD_NAME}
# remote_write:
#   - url: http://host.docker.internal/api/prom/push
#     bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiJkZXZlbG9wbWVudCIsInZlcnNpb24iOjEsImF1ZCI6InJld2UifQ.a7zdFoVYTk_CKR1Cj3h6S3SBGPseS0x3PNJjy4jdvPtWaraDC638QlXu0CeBMf3vLWPBJB0fopbSMQvm6IoPtw
#     queue_config:
#       max_shards: 20
#       max_samples_per_send: 1000

scrape_configs:
  - job_name: 'prometheus'
    static_configs: 
        - targets: ["localhost:9090"]
