version: "3.1"

networks:
  monitor-net:
    driver: bridge

services:

  prometheus:
    image: prom/prometheus:v2.19.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always
    networks:
      - monitor-net
    extra_hosts:
      - "dockerhost:$DOCKERHOST"
#
#  grafana:
#    image: grafana/grafana
#    volumes:
#      - ./grafana/datasources:/etc/grafana/provisioning/datasources
#    user: "104"
#    ports:
#      - 3000:3000
#    restart: always

  nodeexporter:
    image: prom/node-exporter:v1.1.2
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - monitor-net
    expose:
      - 9100
